"""Migration guards.

The schema in ``alembic/versions`` must stay in sync with the ORM metadata: a
model change without a migration is caught here instead of in production.
"""

from __future__ import annotations

import pytest
from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command
from tests.db import alembic_config


def test_migrations_match_the_orm_metadata(migrated_database: str) -> None:
    """``alembic check`` must report no pending autogenerate operations."""
    config = alembic_config(migrated_database)
    try:
        command.check(config)
    except AutogenerateDiffsDetected as diff:  # pragma: no cover - failure path
        pytest.fail(f"ORM metadata and migrations diverged: {diff}")


def test_downgrade_and_upgrade_are_reversible(migrated_database: str) -> None:
    """A full down/up cycle must succeed, including PostgreSQL enum types."""
    config = alembic_config(migrated_database)
    command.downgrade(config, "base")
    command.upgrade(config, "head")
    command.check(config)
