/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Report that the process is running.
         */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Probe PostgreSQL and Redis, answering 503 when any of them is down.
         */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for tokens
         * @description Authenticate the administrator.
         *
         *     Raises:
         *         TooManyLoginAttemptsError: the rate limit for this client was exceeded.
         *         AuthenticationError: wrong username or password.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Issue a new token pair and invalidate the presented refresh token.
         *
         *     Raises:
         *         InvalidTokenError: no token supplied, or it is invalid, expired or revoked.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the refresh token
         * @description Revoke the refresh token and clear the cookie. Idempotent for a stale token.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who am I
         * @description Return the authenticated administrator.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products
         * @description Paginated products, newest first, with search and an activity filter.
         */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        /**
         * Create a product
         * @description Create a product and return it with its deep link.
         *
         *     Raises:
         *         SlugAlreadyExistsError: the slug is taken.
         *         InvalidDeliveryUrlError: the delivery link is not an absolute http(s) URL.
         */
        post: operations["create_product_api_v1_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a product
         * @description Read one product.
         *
         *     Raises:
         *         ProductNotFoundError: no product with this id.
         */
        get: operations["get_product_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a product that was never sold
         * @description Delete a product.
         *
         *     Raises:
         *         ProductNotFoundError: no product with this id.
         *         ConflictError: the product has purchases; deactivate it instead.
         */
        delete: operations["delete_product_api_v1_products__product_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a product
         * @description Apply a partial update.
         *
         *     Only fields present in the request body are touched; sending ``null`` for a
         *     nullable field clears it.
         *
         *     Raises:
         *         ProductNotFoundError: no product with this id.
         *         InvalidPriceError: the update would leave the product with no price.
         *         SlugAlreadyExistsError: the new slug is taken.
         */
        patch: operations["update_product_api_v1_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search purchases
         * @description Search by Telegram id, username, product title or slug, invoice or charge id.
         */
        get: operations["search_purchases_api_v1_purchases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases/{purchase_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check a payment manually and finish it if needed
         * @description Re-check one purchase against the payment provider.
         *
         *     For the support case "I paid but got no link". Idempotent:
         *
         *     * already delivered → reports that, sends nothing;
         *     * paid but undelivered → retries delivery;
         *     * pending → asks CryptoBot for the invoice state, or uses the stored Telegram
         *       charge id, and settles the payment when it is confirmed;
         *     * unpaid, expired or refunded → reported as-is, never "fixed".
         *
         *     Raises:
         *         PurchaseNotFoundError: no purchase with this id.
         *         LockBusyError: a payment or delivery for it is already being processed.
         */
        post: operations["verify_payment_api_v1_purchases__purchase_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases/{purchase_id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the purchased link again
         * @description Re-send the link of an already paid purchase.
         *
         *     Raises:
         *         PurchaseNotFoundError: no purchase with this id.
         *         ConflictError: the purchase is not paid.
         *         LockBusyError: a delivery for it is already running.
         */
        post: operations["resend_delivery_api_v1_purchases__purchase_id__resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard overview
         * @description Today / week / month / all-time revenue, top products and last sales.
         */
        get: operations["overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminResponse
         * @description Who the caller is.
         */
        AdminResponse: {
            /** Username */
            username: string;
        };
        /**
         * BuyerResponse
         * @description The buyer, as shown in listings and search results.
         */
        BuyerResponse: {
            /** Telegram Id */
            telegram_id: number;
            /** Username */
            username: string | null;
            /** First Name */
            first_name: string | null;
            /** Display Name */
            display_name: string;
        };
        /**
         * Currency
         * @description Currencies the shop can charge in.
         * @enum {string}
         */
        Currency: "XTR" | "USDT";
        /**
         * DeliveryAttemptResponse
         * @description Outcome of the delivery attempt triggered by an admin action.
         */
        DeliveryAttemptResponse: {
            status: components["schemas"]["DeliveryStatus"];
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
        };
        /**
         * DeliveryStatus
         * @description Outcome of one delivery attempt sequence.
         * @enum {string}
         */
        DeliveryStatus: "sent" | "already_delivered" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LivenessResponse
         * @description Answered as long as the process can serve HTTP.
         */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "alive";
            /** Version */
            version: string;
        };
        /**
         * LoginRequest
         * @description Administrator credentials.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * OverviewResponse
         * @description Everything the dashboard renders.
         */
        OverviewResponse: {
            today: components["schemas"]["RevenueResponse"];
            week: components["schemas"]["RevenueResponse"];
            month: components["schemas"]["RevenueResponse"];
            total: components["schemas"]["RevenueResponse"];
            /** Top Products */
            top_products: components["schemas"]["TopProductResponse"][];
            /** Recent Purchases */
            recent_purchases: components["schemas"]["PurchaseRecordResponse"][];
            /** Products Total */
            products_total: number;
            /** Products Active */
            products_active: number;
            /** Users Total */
            users_total: number;
        };
        /**
         * PageMeta
         * @description Pagination envelope shared by every listing endpoint.
         */
        PageMeta: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PageResponse[ProductResponse] */
        PageResponse_ProductResponse_: {
            /** Items */
            items: components["schemas"]["ProductResponse"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** PageResponse[PurchaseRecordResponse] */
        PageResponse_PurchaseRecordResponse_: {
            /** Items */
            items: components["schemas"]["PurchaseRecordResponse"][];
            meta: components["schemas"]["PageMeta"];
        };
        /**
         * PaymentProvider
         * @description Payment rails available on a product card.
         * @enum {string}
         */
        PaymentProvider: "stars" | "crypto";
        /**
         * PaymentState
         * @description Provider view of an invoice, used when reconciling lost notifications.
         * @enum {string}
         */
        PaymentState: "pending" | "paid" | "expired";
        /**
         * ProductCreateRequest
         * @description Everything needed to put a product on sale.
         */
        ProductCreateRequest: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Delivery Url */
            delivery_url: string;
            /** Photo File Id */
            photo_file_id?: string | null;
            /** Price Stars */
            price_stars?: number | null;
            /** Price Usdt */
            price_usdt?: number | string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * ProductPatchRequest
         * @description Partial update: only the fields present in the request are applied.
         */
        ProductPatchRequest: {
            /** Slug */
            slug?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Delivery Url */
            delivery_url?: string | null;
            /** Photo File Id */
            photo_file_id?: string | null;
            /** Price Stars */
            price_stars?: number | null;
            /** Price Usdt */
            price_usdt?: number | string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * ProductResponse
         * @description A product as the admin panel shows it, deep link included.
         */
        ProductResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Photo File Id */
            photo_file_id: string | null;
            /** Delivery Url */
            delivery_url: string;
            /** Price Stars */
            price_stars: number | null;
            /** Price Usdt */
            price_usdt: string | null;
            /** Is Active */
            is_active: boolean;
            /** Deep Link */
            deep_link: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProductSummaryResponse
         * @description Just enough product context for a purchase row.
         */
        ProductSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /**
         * PurchaseRecordResponse
         * @description A purchase joined with its buyer and product, for the search table.
         */
        PurchaseRecordResponse: {
            purchase: components["schemas"]["PurchaseResponse"];
            buyer: components["schemas"]["BuyerResponse"];
            product: components["schemas"]["ProductSummaryResponse"];
        };
        /**
         * PurchaseResponse
         * @description One purchase.
         */
        PurchaseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: number;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            provider: components["schemas"]["PaymentProvider"];
            status: components["schemas"]["PurchaseStatus"];
            /** Amount */
            amount: string;
            currency: components["schemas"]["Currency"];
            /** External Id */
            external_id: string;
            /** Telegram Charge Id */
            telegram_charge_id: string | null;
            /** Delivered Url */
            delivered_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Paid At */
            paid_at: string | null;
            /** Delivered At */
            delivered_at: string | null;
        };
        /**
         * PurchaseStatus
         * @description Lifecycle of a single purchase.
         *
         *     ``PENDING`` — invoice issued, no money received yet.
         *     ``PAID`` — payment confirmed by the provider.
         *     ``DELIVERED`` — the delivery link has been sent to the buyer.
         *     ``REFUNDED`` — Telegram Stars refund executed; access is revoked.
         *     ``EXPIRED`` — the invoice was never paid within its lifetime.
         * @enum {string}
         */
        PurchaseStatus: "pending" | "paid" | "delivered" | "refunded" | "expired";
        /**
         * ReadinessResponse
         * @description Aggregated availability of every infrastructure dependency.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Components */
            components: {
                [key: string]: "ok" | "fail";
            };
        };
        /**
         * RefreshRequest
         * @description Body fallback for clients that cannot use the refresh cookie.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * RevenueResponse
         * @description Revenue inside one reporting window.
         */
        RevenueResponse: {
            period: components["schemas"]["StatsPeriod"];
            /** Purchases Count */
            purchases_count: number;
            /** Stars Amount */
            stars_amount: number;
            /** Usdt Amount */
            usdt_amount: string;
        };
        /**
         * StatsPeriod
         * @description Reporting windows offered by the admin dashboard.
         *
         *     Windows are day aligned in UTC: ``TODAY`` starts at midnight today,
         *     ``WEEK`` covers the last 7 days including today, ``MONTH`` the last 30.
         * @enum {string}
         */
        StatsPeriod: "today" | "week" | "month" | "all";
        /**
         * TokenResponse
         * @description Issued credentials. The refresh token is also set as an httpOnly cookie.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Token Type */
            token_type: string;
            /** Access Expires In */
            access_expires_in: number;
            /** Refresh Expires In */
            refresh_expires_in: number;
        };
        /**
         * TopProductResponse
         * @description One row of the best-sellers table.
         */
        TopProductResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Purchases Count */
            purchases_count: number;
            /** Stars Amount */
            stars_amount: number;
            /** Usdt Amount */
            usdt_amount: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationOutcome
         * @description What the check found, and what it did about it.
         * @enum {string}
         */
        VerificationOutcome: "already_delivered" | "delivered_now" | "settled_and_delivered" | "delivery_failed" | "still_unpaid" | "expired_unpaid" | "no_provider_evidence" | "refunded" | "provider_unavailable";
        /**
         * VerificationResponse
         * @description Result of "check payment": what was found and what was done.
         */
        VerificationResponse: {
            /**
             * Purchase Id
             * Format: uuid
             */
            purchase_id: string;
            provider: components["schemas"]["PaymentProvider"];
            outcome: components["schemas"]["VerificationOutcome"];
            /** Resolved */
            resolved: boolean;
            status_before: components["schemas"]["PurchaseStatus"];
            status_after: components["schemas"]["PurchaseStatus"];
            provider_state: components["schemas"]["PaymentState"] | null;
            delivery: components["schemas"]["DeliveryAttemptResponse"] | null;
            /** Detail */
            detail: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminResponse"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                search?: string | null;
                is_active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_ProductResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_v1_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_purchases_api_v1_purchases_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: components["schemas"]["PurchaseStatus"][] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_PurchaseRecordResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_payment_api_v1_purchases__purchase_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_delivery_api_v1_purchases__purchase_id__resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
}
